### ISSUE TITLE
Problem with fetching the data

### ISSUE THREAD

**Issue by kneepdee** [SkiFilmReviews/snow-forecast-sfr#31]
Hi! 
First, thanks for the cool tool! I'm hoping to build a powder alert app based on the data received from snow-forecast-fr.

However, when trying to get the module to work, I run into an issue. 
The error message is below:

`Access to fetch at 'http://www.snow-forecast.com/resorts/Tignes/6day/mid' from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

I'm sorry if it's a stupid problem and caused by me. It's my first time using node modules.

**Comment by MikeSpitz** [comment]
Hey @kneepdee ! Can you share me the code you're using? Are you using this within an app/website/server code?

**Comment by kneepdee** [comment]
Thanks for the reply.

You'll find the code in the repo below. I used Browserify to bundle the code from main.js > bundle.js.
[](https://github.com/kneepdee/snowcast)

What I'm trying to achieve is to get the json with the forecast data and then use that data on my website. Currently it returns undefined.

I tried using a local webserver, same result.

Allow-Control-Allow-Origin: * chrome add-on got rid of the error message but the return value for `console.log(forecast);` is still `undefined`.

I'm sure the problem is on my side somewhere and I'm probably doing something super basic wrong. Sorry, just starting out with all this :)

**Comment by MikeSpitz** [comment]
OK :) Think I can help. IN this file: https://github.com/kneepdee/snowcast/blob/master/main.js

make the code be like so:

```
snow.parseResort('Tignes', 'mid', function(json){
      //json contains the forecast JSON
      console.log(json);
});
```

The way it all works is that you pass a callback function (if you're unsure about this it's definitely worth reading up on, I only mention it because you say you're new to this :) ) to the parseResort method which gets called once the code has finished parsing the site. Let me know if you get anything meaningful when updating the code to be as above.

Essentially you've written your code to work synchronously but because we're accessing a website asynchronously we can't do that. SO we use callbacks. I should probably update this so it works with async/await promises eventually though. 

If you want to do any execution on the result of the forecast you will want to put it in the block of code that has the following comment inside it:
```
      //json contains the forecast JSON
```

Let me know how it goes!

**Comment by kneepdee** [comment]
I changed main.js to the way you suggested and yup, it's now logging an object with weather data like it should. Sweet! 
Thanks so much mate for taking the time and helping a newbie out. I'll try to go from here.

**Comment by MikeSpitz** [comment]
No worries, glad it works! Will close this issue for now but feel free to reach out again if you get stuck
